# title: Rajesh Mondal
# #logo: docs/assets/sun.png
# logo: docs/assets/rotating_Ylm_l12_m6.gif
# description: Research Scholar, IUCAA
# #theme: jekyll-theme-minimal
# # theme: jekyll-theme-cayman
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# plugins:
#   - jekyll-include-cache

title: Rajesh Mondal
description: Research Scholar, IUCAA
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

